import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import Topbar from "@/components/layout/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Clinician web app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen ">
          <div className="flex">
            <div className="w-[16%] fixed left-0 h-full">
              <Navbar />
            </div>
            <div className="lg:flex-1 lg:ml-[16%] bg-[#F6F7F9]  lg:p-8 min-h-screen w-full lg:w-0">
              <Topbar/>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
